# Question 1:
Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [42]:
import numpy as n

In [57]:
a1 = n.array([[1,2,3],[4,5,6],[7,8,9]])
a2 = n.array([[4,2,3],[1,4,8],[5,9,7]])
print('First array is \n',a1,'\n And second array is \n',a2)
print('\n Case 1: Greater than example \n')
print(n.greater(a1 , a2))
print('\n Case 1: Greater than or Equal to example \n')
print(n.greater_equal(a1 , a2))
print('\n Case 1: Lesser than example \n')
print(n.less(a1 , a2))
print('\n Case 1: Lesser than or Equal to example \n')
print(n.less_equal(a1 , a2))

First array is 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
 And second array is 
 [[4 2 3]
 [1 4 8]
 [5 9 7]]

 Case 1: Greater than example 

[[False False False]
 [ True  True False]
 [ True False  True]]

 Case 1: Greater than or Equal to example 

[[False  True  True]
 [ True  True False]
 [ True False  True]]

 Case 1: Lesser than example 

[[ True False False]
 [False False  True]
 [False  True False]]

 Case 1: Lesser than or Equal to example 

[[ True  True  True]
 [False False  True]
 [False  True False]]


In [54]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Question 2:
Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

#### Method 1

In [87]:
a2 = n.full((10,3),5)
b2 = n.zeros((10,1))
c2 = n.ones((10,1))
a2[:,0] = b2[:,0]
#print(a2)
a2[:,1] = c2[:,0]
a2

array([[0, 1, 5],
       [0, 1, 5],
       [0, 1, 5],
       [0, 1, 5],
       [0, 1, 5],
       [0, 1, 5],
       [0, 1, 5],
       [0, 1, 5],
       [0, 1, 5],
       [0, 1, 5]])

#### Method 2

In [92]:
a3 = n.full((3,10),5)
b3 = n.zeros((1,10))
c3 = n.ones((1,10))
a3[1,:] = c3[0,:]
a3[0,:] = b3[0,:]
a3

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

#### Method 3

In [116]:
a4 = n.zeros((3,10))
#b4 = n.array(([0,1,5]))
c4 = n.array(([0],[1],[5]))
d4 = a4 + c4
d4

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

# Question 3:
Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a
given array

In [124]:
a3 #taking a3 from above
i = n.sum(a3)
j = n.sum(a3,axis = 0)
k = n.sum(a3,axis = 1)
print(' Sum of all elements on array is ',i ,'\n Sum of all columns of Array is ', j,'\n Sum of all Rows of Array is ', k, end = '\n')

 Sum of all elements on array is  60 
 Sum of all columns of Array is  [6 6 6 6 6 6 6 6 6 6] 
 Sum of all Rows of Array is  [ 0 10 50]


# Question 4:
Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [139]:
x4 = n.full((3,3),2)
y4 = n.full((3,3),4)

add = n.add(x4,y4)
subt = n.subtract(y4,x4)
multiply = n.multiply(x4,y4)
divide = n.divide(y4,x4)
print('Array 1 is \n',x4,'\nArray 2 is \n',y4)
print(' Addition of the two arrays is \n',add,'\n Subtraction of the two arrays is  \n', subt,'\n Multiplication of the two arrays is  \n', multiply,'\n Division of the two arrays is \n', divide)

Array 1 is 
 [[2 2 2]
 [2 2 2]
 [2 2 2]] 
Array 2 is 
 [[4 4 4]
 [4 4 4]
 [4 4 4]]
 Addition of the two arrays is 
 [[6 6 6]
 [6 6 6]
 [6 6 6]] 
 Subtraction of the two arrays is  
 [[2 2 2]
 [2 2 2]
 [2 2 2]] 
 Multiplication of the two arrays is  
 [[8 8 8]
 [8 8 8]
 [8 8 8]] 
 Division of the two arrays is 
 [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


# Question 5:
Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in
degree.

In [140]:
import math
import scipy

In [162]:
a5 = n.array((0, 30, 45, 60, 90))      #array in degrees    
sine = numpy.sin(n.radians(a5))
cosine = numpy.cos(n.radians(a5))
tan = numpy.tan(n.radians(a5))

print('For given Array: \n', a5, '\n Result of applying Sine function to a5 is \n',sine,'\n Result of applying Cosine function to a5 is \n',cosine,'\n Result of applying Tangent function to a5 is \n',tan)

For given Array: 
 [ 0 30 45 60 90] 
 Result of applying Sine function to a5 is 
 [0.         0.5        0.70710678 0.8660254  1.        ] 
 Result of applying Cosine function to a5 is 
 [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17] 
 Result of applying Tangent function to a5 is 
 [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


# Pandas is not yet taught or discussed by Arindam sir as on 14 Sept. Only one lecture is competed and numpy & scipy was discussed. Next lecture is scheduled on Tuesday (16 Sept). Since assignment is to be submitted by 14 Sept, Numpy & Scipy Questions are solved and submitting the same.