# Question 1:
Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [42]:
import numpy as n

In [57]:
a1 = n.array([[1,2,3],[4,5,6],[7,8,9]])
a2 = n.array([[4,2,3],[1,4,8],[5,9,7]])
print('First array is \n',a1,'\n And second array is \n',a2)
print('\n Case 1: Greater than example \n')
print(n.greater(a1 , a2))
print('\n Case 1: Greater than or Equal to example \n')
print(n.greater_equal(a1 , a2))
print('\n Case 1: Lesser than example \n')
print(n.less(a1 , a2))
print('\n Case 1: Lesser than or Equal to example \n')
print(n.less_equal(a1 , a2))

First array is 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
 And second array is 
 [[4 2 3]
 [1 4 8]
 [5 9 7]]

 Case 1: Greater than example 

[[False False False]
 [ True  True False]
 [ True False  True]]

 Case 1: Greater than or Equal to example 

[[False  True  True]
 [ True  True False]
 [ True False  True]]

 Case 1: Lesser than example 

[[ True False False]
 [False False  True]
 [False  True False]]

 Case 1: Lesser than or Equal to example 

[[ True  True  True]
 [False False  True]
 [False  True False]]


In [54]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Question 2:
Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

#### Method 1

In [87]:
a2 = n.full((10,3),5)
b2 = n.zeros((10,1))
c2 = n.ones((10,1))
a2[:,0] = b2[:,0]
#print(a2)
a2[:,1] = c2[:,0]
a2

array([[0, 1, 5],
       [0, 1, 5],
       [0, 1, 5],
       [0, 1, 5],
       [0, 1, 5],
       [0, 1, 5],
       [0, 1, 5],
       [0, 1, 5],
       [0, 1, 5],
       [0, 1, 5]])

#### Method 2

In [92]:
a3 = n.full((3,10),5)
b3 = n.zeros((1,10))
c3 = n.ones((1,10))
a3[1,:] = c3[0,:]
a3[0,:] = b3[0,:]
a3

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

#### Method 3

In [116]:
a4 = n.zeros((3,10))
#b4 = n.array(([0,1,5]))
c4 = n.array(([0],[1],[5]))
d4 = a4 + c4
d4

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

# Question 3:
Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a
given array

In [124]:
a3 #taking a3 from above
i = n.sum(a3)
j = n.sum(a3,axis = 0)
k = n.sum(a3,axis = 1)
print(' Sum of all elements on array is ',i ,'\n Sum of all columns of Array is ', j,'\n Sum of all Rows of Array is ', k, end = '\n')

 Sum of all elements on array is  60 
 Sum of all columns of Array is  [6 6 6 6 6 6 6 6 6 6] 
 Sum of all Rows of Array is  [ 0 10 50]


# Question 4:
Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [139]:
x4 = n.full((3,3),2)
y4 = n.full((3,3),4)

add = n.add(x4,y4)
subt = n.subtract(y4,x4)
multiply = n.multiply(x4,y4)
divide = n.divide(y4,x4)
print('Array 1 is \n',x4,'\nArray 2 is \n',y4)
print(' Addition of the two arrays is \n',add,'\n Subtraction of the two arrays is  \n', subt,'\n Multiplication of the two arrays is  \n', multiply,'\n Division of the two arrays is \n', divide)

Array 1 is 
 [[2 2 2]
 [2 2 2]
 [2 2 2]] 
Array 2 is 
 [[4 4 4]
 [4 4 4]
 [4 4 4]]
 Addition of the two arrays is 
 [[6 6 6]
 [6 6 6]
 [6 6 6]] 
 Subtraction of the two arrays is  
 [[2 2 2]
 [2 2 2]
 [2 2 2]] 
 Multiplication of the two arrays is  
 [[8 8 8]
 [8 8 8]
 [8 8 8]] 
 Division of the two arrays is 
 [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


# Question 5:
Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in
degree.

In [140]:
import math
import scipy

In [162]:
a5 = n.array((0, 30, 45, 60, 90))      #array in degrees    
sine = numpy.sin(n.radians(a5))
cosine = numpy.cos(n.radians(a5))
tan = numpy.tan(n.radians(a5))

print('For given Array: \n', a5, '\n Result of applying Sine function to a5 is \n',sine,'\n Result of applying Cosine function to a5 is \n',cosine,'\n Result of applying Tangent function to a5 is \n',tan)

For given Array: 
 [ 0 30 45 60 90] 
 Result of applying Sine function to a5 is 
 [0.         0.5        0.70710678 0.8660254  1.        ] 
 Result of applying Cosine function to a5 is 
 [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17] 
 Result of applying Tangent function to a5 is 
 [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


# Question 6:
Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the
index labels

In [12]:
import pandas as pd
a = {'Name':['Sharvari','Shounak','Atharva','Sanjay','Chintu','Pintu'],'Gender':['F','M','M','M','F','F'],'Education':[17,18,15,19,8,10],'Score':[99,87,98,91,121,113]}
b = ['R1','R2','R3','R4','R5','R6']

In [13]:
d = pd.DataFrame(a,b)
d

Name Gender  Education  Score
R1  Sharvari      F         17     99
R2   Shounak      M         18     87
R3   Atharva      M         15     98
R4    Sanjay      M         19     91
R5    Chintu      F          8    121
R6     Pintu      F         10    113

# Question 7:
Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.

In [21]:
a = {'Name':['Sharvari','Shounak','Atharva','Sanjay','Chintu','Pintu'],'Gender':['F','M','M','M','F','F'],'Education':[17,18,15,19,8,10],'Score':[99,87,98,91,121,113]}
b = ['R1','R2','R3','R4','R5','R6']
d = pd.DataFrame(a,b)
print(d[['Name','Score']])

        Name  Score
R1  Sharvari     99
R2   Shounak     87
R3   Atharva     98
R4    Sanjay     91
R5    Chintu    121
R6     Pintu    113


# Question 8:
Write a Pandas program to join the two given dataframes along rows and assign all data.

In [109]:
x = {'Name':['Sharvari','Shounak','Atharva','Sanjay','Chintu','Pintu'],'City':['Pune','Pune','New York','Dublin','Kolhapur','Dukkarwadi'],'DIstance Travelled':[717,180,1555,9819,888,170]}
y = {'Name':['Tom','Chuck','Rock'],'City':['Florida','Jupiter','Mars'],'DIstance Travelled':[1223,3456,876]}
d1 = pd.DataFrame(y)
d2 = pd.DataFrame(x)

In [110]:
d1.to_csv('File_2.csv')   #Forming file 1 & 2
d2.to_csv('File_3.csv')

In [111]:
#Reading both the files

import os
os.chdir(r'C:\Users\shoun\Coding\AIML')
x = pd.read_csv('File_3.csv')
y = pd.read_csv('File_2.csv')


In [120]:
#Joining the 2 data frame files using append
x.append(y)

Unnamed: 0      Name        City  DIstance Travelled
0           0  Sharvari        Pune                 717
1           1   Shounak        Pune                 180
2           2   Atharva    New York                1555
3           3    Sanjay      Dublin                9819
4           4    Chintu    Kolhapur                 888
5           5     Pintu  Dukkarwadi                 170
0           0       Tom     Florida                1223
1           1     Chuck     Jupiter                3456
2           2      Rock        Mars                 876

In [119]:
#Joining the 2 data frame files using concat
cnct = pd.concat([x,y])
cnct

Unnamed: 0      Name        City  DIstance Travelled
0           0  Sharvari        Pune                 717
1           1   Shounak        Pune                 180
2           2   Atharva    New York                1555
3           3    Sanjay      Dublin                9819
4           4    Chintu    Kolhapur                 888
5           5     Pintu  Dukkarwadi                 170
0           0       Tom     Florida                1223
1           1     Chuck     Jupiter                3456
2           2      Rock        Mars                 876

# Question 9:
Write a Pandas program to detect missing values of a given DataFrame. Display True or False.

In [87]:
x = {'Name':['Sharvari','Shounak','Atharva','Sanjay'],'Fovourite Movie':['Gladiator','LOTR','Avengers','Payne'],'Fav Sports':['Cricket','Football','Cricket','Tennis']}
d3 = pd.DataFrame(x)


In [88]:
d3.to_csv('File_3')

In [101]:
z = pd.read_csv('File_3')
g = x.merge(z,on = 'Name',how = 'outer')
print('Merge dataframe is:' )
print(g)
print('\n Displaying missing values as True or False')
g.isna()

Merge dataframe is:
  Unnamed: 0_x      Name Gender  Education  Score  Unnamed: 0_y  \
0           R1  Sharvari      F         17     99           0.0   
1           R2   Shounak      M         18     87           1.0   
2           R3   Atharva      M         15     98           2.0   
3           R4    Sanjay      M         19     91           3.0   
4           R5    Chintu      F          8    121           NaN   
5           R6     Pintu      F         10    113           NaN   

  Fovourite Movie Fav Sports  
0       Gladiator    Cricket  
1            LOTR   Football  
2        Avengers    Cricket  
3           Payne     Tennis  
4             NaN        NaN  
5             NaN        NaN  

 Displaying missing values as True or False


Unnamed: 0_x   Name  Gender  Education  Score  Unnamed: 0_y  \
0         False  False   False      False  False         False   
1         False  False   False      False  False         False   
2         False  False   False      False  False         False   
3         False  False   False      False  False         False   
4         False  False   False      False  False          True   
5         False  False   False      False  False          True   

   Fovourite Movie  Fav Sports  
0            False       False  
1            False       False  
2            False       False  
3            False       False  
4             True        True  
5             True        True

# Question 10:
Write a Pandas program to create and display a one-dimensional array-like object containing an array of
data.

In [131]:
ab = ('a','b','c','d','e','f','g','h','i','j')
a = pd.Series(list(ab), index = range(10))
a

0    a
1    b
2    c
3    d
4    e
5    f
6    g
7    h
8    i
9    j
dtype: object